import javafx.application.Application;
import javafx.scene.Scene;
import javafx.stage.Stage;
import javafx.scene.Node;
import javafx.scene.text.TextAlignment;
import javafx.geometry.Pos;
import javafx.scene.control.ContentDisplay;
import javafx.event.Event;
import javafx.scene.input.KeyEvent;
import javafx.scene.input.MouseEvent;
import javafx.scene.Group;
import javafx.scene.layout.VBox;
import javafx.scene.control.TextField;
import javafx.scene.layout.HBox;
import javafx.scene.control.Button;
import javafx.scene.shape.Sphere;

public class Code extends Application{

public static void main(String[] args){launch(args);}

@Override
public void start(Stage primaryStage) throws Exception {
Group group1 = new Group();
group1.setId(null + "");
group1.setOpacity(1.0);
group1.setScaleY(1.0);
group1.setScaleX(1.0);
group1.setLayoutX(0.0);
group1.setTranslateX(-253.33333333333334);
group1.setLayoutY(0.0);
group1.setTranslateY(-112.0);
group1.setRotate(0.0);
group1.setScaleZ(1.0);
group1.setTranslateZ(0.0);
VBox vbox2 = new VBox();
group1.getChildren().add(vbox2);

vbox2.setSpacing(0.0);
vbox2.setAlignment(Pos.TOP_LEFT);
vbox2.setMinHeight(-1.0);
vbox2.setMaxWidth(1280.0);
vbox2.setMaxHeight(720.0);
vbox2.setMinWidth(-1.0);
vbox2.setPrefHeight(-1.0);
vbox2.setBorder(null);
vbox2.setPrefWidth(-1.0);
vbox2.setOpaqueInsets(null);
vbox2.setShape(null);
vbox2.setId(null + "");
vbox2.setOpacity(1.0);
vbox2.setScaleY(1.0);
vbox2.setScaleX(1.0);
vbox2.setLayoutX(0.0);
vbox2.setTranslateX(253.33333333333334);
vbox2.setLayoutY(0.0);
vbox2.setTranslateY(112.0);
vbox2.setRotate(0.0);
vbox2.setScaleZ(1.0);
vbox2.setTranslateZ(0.0);
TextField textfield1 = new TextField();
vbox2.getChildren().add(textfield1);

textfield1.setPrefColumnCount(12);
textfield1.setAlignment(Pos.CENTER_LEFT);
textfield1.setText("2");
textfield1.setTextFormatter(null);
textfield1.setTooltip(null);
textfield1.setContextMenu(null);
textfield1.setMinHeight(-1.0);
textfield1.setMaxWidth(-1.0);
textfield1.setMaxHeight(-1.0);
textfield1.setMinWidth(-1.0);
textfield1.setPrefHeight(-1.0);
textfield1.setBorder(null);
textfield1.setPrefWidth(-1.0);
textfield1.setOpaqueInsets(null);
textfield1.setShape(null);
textfield1.setId(1 + "");
textfield1.setOpacity(1.0);
textfield1.setScaleY(1.0);
textfield1.setScaleX(1.0);
textfield1.setLayoutX(0.0);
textfield1.setTranslateX(0.0);
textfield1.setLayoutY(0.0);
textfield1.setTranslateY(0.0);
textfield1.setRotate(0.0);
textfield1.setScaleZ(1.0);
textfield1.setTranslateZ(0.0);
TextField textfield2 = new TextField();
vbox2.getChildren().add(textfield2);

textfield2.setPrefColumnCount(12);
textfield2.setAlignment(Pos.CENTER_LEFT);
textfield2.setTextFormatter(null);
textfield2.setTooltip(null);
textfield2.setContextMenu(null);
textfield2.setMinHeight(-1.0);
textfield2.setMaxWidth(-1.0);
textfield2.setMaxHeight(-1.0);
textfield2.setMinWidth(-1.0);
textfield2.setPrefHeight(-1.0);
textfield2.setBorder(null);
textfield2.setPrefWidth(-1.0);
textfield2.setOpaqueInsets(null);
textfield2.setShape(null);
textfield2.setId(2 + "");
textfield2.setOpacity(1.0);
textfield2.setScaleY(1.0);
textfield2.setScaleX(1.0);
textfield2.setLayoutX(0.0);
textfield2.setTranslateX(0.0);
textfield2.setLayoutY(25.0);
textfield2.setTranslateY(0.0);
textfield2.setRotate(0.0);
textfield2.setScaleZ(1.0);
textfield2.setTranslateZ(0.0);
HBox hbox3 = new HBox();
vbox2.getChildren().add(hbox3);

hbox3.setSpacing(0.0);
hbox3.setAlignment(Pos.TOP_LEFT);
hbox3.setMinHeight(-1.0);
hbox3.setMaxWidth(-1.0);
hbox3.setMaxHeight(-1.0);
hbox3.setMinWidth(-1.0);
hbox3.setPrefHeight(-1.0);
hbox3.setBorder(null);
hbox3.setPrefWidth(-1.0);
hbox3.setOpaqueInsets(null);
hbox3.setShape(null);
hbox3.setId(3 + "");
hbox3.setOpacity(1.0);
hbox3.setScaleY(1.0);
hbox3.setScaleX(1.0);
hbox3.setLayoutX(0.0);
hbox3.setTranslateX(0.0);
hbox3.setLayoutY(50.0);
hbox3.setTranslateY(0.0);
hbox3.setRotate(0.0);
hbox3.setScaleZ(1.0);
hbox3.setTranslateZ(0.0);
Button button4 = new Button();
hbox3.getChildren().add(button4);

button4.setGraphic(null);
button4.setText("twice");
button4.setAlignment(Pos.CENTER);
button4.setLineSpacing(0.0);
button4.setContentDisplay(ContentDisplay.LEFT);
button4.setTextAlignment(TextAlignment.LEFT);
button4.setGraphicTextGap(4.0);
button4.setTooltip(null);
button4.setContextMenu(null);
button4.setMinHeight(-1.0);
button4.setMaxWidth(-1.0);
button4.setMaxHeight(-1.0);
button4.setMinWidth(-1.0);
button4.setPrefHeight(-1.0);
button4.setBorder(null);
button4.setPrefWidth(-1.0);
button4.setOpaqueInsets(null);
button4.setShape(null);
button4.setId(4 + "");
button4.setOpacity(1.0);
button4.setScaleY(1.0);
button4.setScaleX(1.0);
button4.setLayoutX(0.0);
button4.setTranslateX(0.0);
button4.setLayoutY(0.0);
button4.setTranslateY(0.0);
button4.setRotate(0.0);
button4.setScaleZ(1.0);
button4.setTranslateZ(0.0);
Button button5 = new Button();
hbox3.getChildren().add(button5);

button5.setGraphic(null);
button5.setText("sizeUp");
button5.setAlignment(Pos.CENTER);
button5.setLineSpacing(0.0);
button5.setContentDisplay(ContentDisplay.LEFT);
button5.setTextAlignment(TextAlignment.LEFT);
button5.setGraphicTextGap(4.0);
button5.setTooltip(null);
button5.setContextMenu(null);
button5.setMinHeight(-1.0);
button5.setMaxWidth(-1.0);
button5.setMaxHeight(-1.0);
button5.setMinWidth(-1.0);
button5.setPrefHeight(-1.0);
button5.setBorder(null);
button5.setPrefWidth(-1.0);
button5.setOpaqueInsets(null);
button5.setShape(null);
button5.setId(5 + "");
button5.setOpacity(1.0);
button5.setScaleY(1.0);
button5.setScaleX(1.0);
button5.setLayoutX(44.0);
button5.setTranslateX(0.0);
button5.setLayoutY(0.0);
button5.setTranslateY(0.0);
button5.setRotate(0.0);
button5.setScaleZ(1.0);
button5.setTranslateZ(0.0);
Button button6 = new Button();
hbox3.getChildren().add(button6);

button6.setGraphic(null);
button6.setText("sizeDown");
button6.setAlignment(Pos.CENTER);
button6.setLineSpacing(0.0);
button6.setContentDisplay(ContentDisplay.LEFT);
button6.setTextAlignment(TextAlignment.LEFT);
button6.setGraphicTextGap(4.0);
button6.setTooltip(null);
button6.setContextMenu(null);
button6.setMinHeight(-1.0);
button6.setMaxWidth(-1.0);
button6.setMaxHeight(-1.0);
button6.setMinWidth(-1.0);
button6.setPrefHeight(-1.0);
button6.setBorder(null);
button6.setPrefWidth(-1.0);
button6.setOpaqueInsets(null);
button6.setShape(null);
button6.setId(6 + "");
button6.setOpacity(1.0);
button6.setScaleY(1.0);
button6.setScaleX(1.0);
button6.setLayoutX(95.0);
button6.setTranslateX(0.0);
button6.setLayoutY(0.0);
button6.setTranslateY(0.0);
button6.setRotate(0.0);
button6.setScaleZ(1.0);
button6.setTranslateZ(0.0);
Button button7 = new Button();
hbox3.getChildren().add(button7);

button7.setGraphic(null);
button7.setText("Subtract");
button7.setAlignment(Pos.CENTER);
button7.setLineSpacing(0.0);
button7.setContentDisplay(ContentDisplay.LEFT);
button7.setTextAlignment(TextAlignment.LEFT);
button7.setGraphicTextGap(4.0);
button7.setTooltip(null);
button7.setContextMenu(null);
button7.setMinHeight(-1.0);
button7.setMaxWidth(-1.0);
button7.setMaxHeight(-1.0);
button7.setMinWidth(-1.0);
button7.setPrefHeight(-1.0);
button7.setBorder(null);
button7.setPrefWidth(-1.0);
button7.setOpaqueInsets(null);
button7.setShape(null);
button7.setId(7 + "");
button7.setOpacity(1.0);
button7.setScaleY(1.0);
button7.setScaleX(1.0);
button7.setLayoutX(162.0);
button7.setTranslateX(0.0);
button7.setLayoutY(0.0);
button7.setTranslateY(0.0);
button7.setRotate(0.0);
button7.setScaleZ(1.0);
button7.setTranslateZ(0.0);
TextField textfield8 = new TextField();
vbox2.getChildren().add(textfield8);

textfield8.setPrefColumnCount(12);
textfield8.setAlignment(Pos.CENTER_LEFT);
textfield8.setTextFormatter(null);
textfield8.setTooltip(null);
textfield8.setContextMenu(null);
textfield8.setMinHeight(-1.0);
textfield8.setMaxWidth(-1.0);
textfield8.setMaxHeight(-1.0);
textfield8.setMinWidth(-1.0);
textfield8.setPrefHeight(-1.0);
textfield8.setBorder(null);
textfield8.setPrefWidth(-1.0);
textfield8.setOpaqueInsets(null);
textfield8.setShape(null);
textfield8.setId(8 + "");
textfield8.setOpacity(1.0);
textfield8.setScaleY(1.0);
textfield8.setScaleX(1.0);
textfield8.setLayoutX(0.0);
textfield8.setTranslateX(0.0);
textfield8.setLayoutY(75.0);
textfield8.setTranslateY(0.0);
textfield8.setRotate(0.0);
textfield8.setScaleZ(1.0);
textfield8.setTranslateZ(0.0);
Sphere sphere9 = new Sphere();
vbox2.getChildren().add(sphere9);

sphere9.setRadius(1.0);
sphere9.setMaterial(null);
sphere9.setId(9 + "");
sphere9.setOpacity(1.0);
sphere9.setScaleY(1.0);
sphere9.setScaleX(1.0);
sphere9.setLayoutX(1.0);
sphere9.setTranslateX(0.0);
sphere9.setLayoutY(101.0);
sphere9.setTranslateY(0.0);
sphere9.setRotate(0.0);
sphere9.setScaleZ(1.0);
sphere9.setTranslateZ(0.0);

Node node4_0 = group1.lookup("#4");
Node input4_1 = group1.lookup("#1");
Node output4_8 = group1.lookup("#8");


Scene scene1 = new Scene(group1,1280,720);
primaryStage.setScene(scene1);
primaryStage.sizeToScene();
primaryStage.show();
}

}
